export const keywords = [
  "Brand strategy consulting",
  "Brand identity design solutions",
  "Logo design services",
  "Visual style guidelines creation",
  "Website design and development",
  "Landing page design services",
  "E-commerce website development",
  "Mobile app design and development",
  "Content creation services",
  "Social media management solutions",
  "Social media advertising strategies",
  "Influencer marketing campaigns",
  "Search engine optimization (SEO)",
  "Pay-per-click (PPC) advertising",
  "Remarketing campaign management",
  "Email marketing campaigns",
  "Marketing automation solutions",
  "Customer persona development",
  "User experience (UX) design",
  "User interface (UI) design services",
  "Interactive website features",
  "Graphic design services",
  "Data analytics and reporting",
  "Chatbot development and implementation",
  "Virtual reality (VR) experiences",
  "Augmented reality (AR) solutions",
  "Brand strategy planning",
  "Brand identity development",
  "Logo design and branding",
  "Visual style guide creation",
  "Website design and customization",
  "Landing page optimization",
  "E-commerce platform development",
  "Mobile app design and optimization",
  "Content creation and marketing",
  "Social media management and advertising",
  "AI-powered brand optimization",
  "Artificial intelligence-driven brand innovation",
  "Web 3",
  "Blockchain",
  "WordPress",
  "Next JS",
  "Webflow",
  "aeoyu",
  "8 of tentacles",
];
